/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created: Wed 12. Dec 02:27:06 2012
**      by: Qt User Interface Compiler version 4.8.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QSpinBox>
#include <QtGui/QTabWidget>
#include <QtGui/QTextBrowser>
#include <QtGui/QTreeView>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindowClass
{
public:
    QWidget *centralWidget;
    QComboBox *deviceBox;
    QPushButton *sendBtn;
    QTabWidget *ipTabs;
    QWidget *ip4Tab;
    QLabel *label_4;
    QLineEdit *ip4ver;
    QLabel *label_5;
    QLineEdit *ip4ihl;
    QLineEdit *ip4tos;
    QLabel *label_6;
    QLineEdit *ip4len;
    QLabel *label_7;
    QLineEdit *ip4id;
    QLineEdit *ip4offset;
    QLineEdit *ip4proto;
    QLineEdit *ip4checksum;
    QLabel *label_8;
    QCheckBox *ip4res;
    QCheckBox *ip4df;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QCheckBox *ip4mf;
    QLabel *label_12;
    QLabel *label_13;
    QSpinBox *ip4ttl;
    QLabel *label_14;
    QLabel *label_15;
    QLineEdit *ip4src;
    QLabel *label_16;
    QLineEdit *ip4dest;
    QLabel *label_17;
    QWidget *ip6Tab;
    QTabWidget *transportTabs;
    QWidget *udpTab;
    QLineEdit *udpSrc;
    QLineEdit *udpDst;
    QLineEdit *udpLen;
    QLineEdit *udpChecksum;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QWidget *tcpTab;
    QLineEdit *tcpSrc;
    QLineEdit *tcpSeqNum;
    QLineEdit *tcpDst;
    QLineEdit *tcpAckNum;
    QLineEdit *tcpOffset;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QCheckBox *tcpRes0;
    QCheckBox *tcpRes1;
    QCheckBox *tcpRes2;
    QLabel *label_27;
    QCheckBox *tcpSyn;
    QCheckBox *tcpRst;
    QCheckBox *tcpAck;
    QCheckBox *tcpNs;
    QCheckBox *tcpEce;
    QCheckBox *tcpUrg;
    QCheckBox *tcpFin;
    QCheckBox *tcpPsh;
    QCheckBox *tcpCwr;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLineEdit *tcpWs;
    QLineEdit *tcpChecksum;
    QLineEdit *tcpUrgPointer;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QWidget *icmpTab;
    QLineEdit *icmpType;
    QLineEdit *icmpCode;
    QLineEdit *icmpChecksum;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLineEdit *icmpId;
    QLineEdit *icmpSeq;
    QLineEdit *icmpData;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QTabWidget *ethTabs;
    QWidget *ethTab;
    QLineEdit *ethSrc;
    QLineEdit *ethDst;
    QLineEdit *ethType;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QTabWidget *etcTabs;
    QWidget *deviceDescriptionTab;
    QTextBrowser *deviceDescription;
    QWidget *savedPacketsTab;
    QPushButton *selectPacketBtn;
    QPushButton *loadPacketFileBtn;
    QTreeView *packetsView;
    QPushButton *savePacketBtn;
    QCheckBox *sendAll;
    QPushButton *stopBtn;

    void setupUi(QMainWindow *MainWindowClass)
    {
        if (MainWindowClass->objectName().isEmpty())
            MainWindowClass->setObjectName(QString::fromUtf8("MainWindowClass"));
        MainWindowClass->resize(812, 409);
        centralWidget = new QWidget(MainWindowClass);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        deviceBox = new QComboBox(centralWidget);
        deviceBox->setObjectName(QString::fromUtf8("deviceBox"));
        deviceBox->setGeometry(QRect(10, 10, 391, 22));
        sendBtn = new QPushButton(centralWidget);
        sendBtn->setObjectName(QString::fromUtf8("sendBtn"));
        sendBtn->setGeometry(QRect(10, 380, 75, 23));
        ipTabs = new QTabWidget(centralWidget);
        ipTabs->setObjectName(QString::fromUtf8("ipTabs"));
        ipTabs->setGeometry(QRect(10, 140, 391, 231));
        ip4Tab = new QWidget();
        ip4Tab->setObjectName(QString::fromUtf8("ip4Tab"));
        label_4 = new QLabel(ip4Tab);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(20, 10, 41, 16));
        ip4ver = new QLineEdit(ip4Tab);
        ip4ver->setObjectName(QString::fromUtf8("ip4ver"));
        ip4ver->setGeometry(QRect(10, 30, 61, 20));
        label_5 = new QLabel(ip4Tab);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(90, 10, 21, 16));
        ip4ihl = new QLineEdit(ip4Tab);
        ip4ihl->setObjectName(QString::fromUtf8("ip4ihl"));
        ip4ihl->setGeometry(QRect(80, 30, 71, 20));
        ip4tos = new QLineEdit(ip4Tab);
        ip4tos->setObjectName(QString::fromUtf8("ip4tos"));
        ip4tos->setGeometry(QRect(160, 30, 71, 20));
        label_6 = new QLabel(ip4Tab);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(170, 10, 21, 16));
        ip4len = new QLineEdit(ip4Tab);
        ip4len->setObjectName(QString::fromUtf8("ip4len"));
        ip4len->setGeometry(QRect(240, 30, 131, 20));
        label_7 = new QLabel(ip4Tab);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(250, 10, 71, 16));
        ip4id = new QLineEdit(ip4Tab);
        ip4id->setObjectName(QString::fromUtf8("ip4id"));
        ip4id->setGeometry(QRect(10, 80, 141, 20));
        ip4offset = new QLineEdit(ip4Tab);
        ip4offset->setObjectName(QString::fromUtf8("ip4offset"));
        ip4offset->setGeometry(QRect(240, 80, 131, 20));
        ip4proto = new QLineEdit(ip4Tab);
        ip4proto->setObjectName(QString::fromUtf8("ip4proto"));
        ip4proto->setGeometry(QRect(80, 130, 121, 20));
        ip4checksum = new QLineEdit(ip4Tab);
        ip4checksum->setObjectName(QString::fromUtf8("ip4checksum"));
        ip4checksum->setGeometry(QRect(210, 130, 161, 20));
        label_8 = new QLabel(ip4Tab);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(20, 60, 51, 16));
        ip4res = new QCheckBox(ip4Tab);
        ip4res->setObjectName(QString::fromUtf8("ip4res"));
        ip4res->setGeometry(QRect(160, 80, 16, 17));
        ip4df = new QCheckBox(ip4Tab);
        ip4df->setObjectName(QString::fromUtf8("ip4df"));
        ip4df->setGeometry(QRect(190, 80, 16, 17));
        label_9 = new QLabel(ip4Tab);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(160, 60, 21, 16));
        label_10 = new QLabel(ip4Tab);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(190, 60, 16, 16));
        label_11 = new QLabel(ip4Tab);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(220, 60, 16, 16));
        ip4mf = new QCheckBox(ip4Tab);
        ip4mf->setObjectName(QString::fromUtf8("ip4mf"));
        ip4mf->setGeometry(QRect(220, 80, 16, 17));
        label_12 = new QLabel(ip4Tab);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(250, 60, 91, 16));
        label_13 = new QLabel(ip4Tab);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(20, 110, 21, 16));
        ip4ttl = new QSpinBox(ip4Tab);
        ip4ttl->setObjectName(QString::fromUtf8("ip4ttl"));
        ip4ttl->setGeometry(QRect(10, 130, 61, 22));
        ip4ttl->setMaximum(255);
        label_14 = new QLabel(ip4Tab);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(90, 110, 46, 13));
        label_15 = new QLabel(ip4Tab);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(240, 110, 51, 16));
        ip4src = new QLineEdit(ip4Tab);
        ip4src->setObjectName(QString::fromUtf8("ip4src"));
        ip4src->setGeometry(QRect(10, 180, 171, 20));
        label_16 = new QLabel(ip4Tab);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(20, 160, 41, 16));
        ip4dest = new QLineEdit(ip4Tab);
        ip4dest->setObjectName(QString::fromUtf8("ip4dest"));
        ip4dest->setGeometry(QRect(190, 180, 181, 20));
        label_17 = new QLabel(ip4Tab);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(200, 160, 61, 16));
        ipTabs->addTab(ip4Tab, QString());
        ip6Tab = new QWidget();
        ip6Tab->setObjectName(QString::fromUtf8("ip6Tab"));
        ipTabs->addTab(ip6Tab, QString());
        transportTabs = new QTabWidget(centralWidget);
        transportTabs->setObjectName(QString::fromUtf8("transportTabs"));
        transportTabs->setGeometry(QRect(410, 140, 391, 231));
        udpTab = new QWidget();
        udpTab->setObjectName(QString::fromUtf8("udpTab"));
        udpSrc = new QLineEdit(udpTab);
        udpSrc->setObjectName(QString::fromUtf8("udpSrc"));
        udpSrc->setGeometry(QRect(10, 30, 170, 20));
        udpDst = new QLineEdit(udpTab);
        udpDst->setObjectName(QString::fromUtf8("udpDst"));
        udpDst->setGeometry(QRect(200, 30, 170, 20));
        udpLen = new QLineEdit(udpTab);
        udpLen->setObjectName(QString::fromUtf8("udpLen"));
        udpLen->setGeometry(QRect(10, 80, 170, 20));
        udpChecksum = new QLineEdit(udpTab);
        udpChecksum->setObjectName(QString::fromUtf8("udpChecksum"));
        udpChecksum->setGeometry(QRect(200, 80, 170, 20));
        label_18 = new QLabel(udpTab);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(20, 10, 71, 16));
        label_19 = new QLabel(udpTab);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(210, 10, 91, 16));
        label_20 = new QLabel(udpTab);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(20, 60, 91, 16));
        label_21 = new QLabel(udpTab);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(210, 60, 61, 20));
        transportTabs->addTab(udpTab, QString());
        tcpTab = new QWidget();
        tcpTab->setObjectName(QString::fromUtf8("tcpTab"));
        tcpSrc = new QLineEdit(tcpTab);
        tcpSrc->setObjectName(QString::fromUtf8("tcpSrc"));
        tcpSrc->setGeometry(QRect(10, 30, 170, 20));
        tcpSeqNum = new QLineEdit(tcpTab);
        tcpSeqNum->setObjectName(QString::fromUtf8("tcpSeqNum"));
        tcpSeqNum->setGeometry(QRect(10, 80, 121, 20));
        tcpDst = new QLineEdit(tcpTab);
        tcpDst->setObjectName(QString::fromUtf8("tcpDst"));
        tcpDst->setGeometry(QRect(200, 30, 170, 20));
        tcpAckNum = new QLineEdit(tcpTab);
        tcpAckNum->setObjectName(QString::fromUtf8("tcpAckNum"));
        tcpAckNum->setGeometry(QRect(140, 80, 131, 20));
        tcpOffset = new QLineEdit(tcpTab);
        tcpOffset->setObjectName(QString::fromUtf8("tcpOffset"));
        tcpOffset->setGeometry(QRect(280, 80, 91, 20));
        label_22 = new QLabel(tcpTab);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(20, 10, 71, 16));
        label_23 = new QLabel(tcpTab);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(220, 10, 91, 16));
        label_24 = new QLabel(tcpTab);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(20, 60, 91, 16));
        label_25 = new QLabel(tcpTab);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(145, 60, 121, 16));
        label_26 = new QLabel(tcpTab);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(290, 60, 46, 13));
        tcpRes0 = new QCheckBox(tcpTab);
        tcpRes0->setObjectName(QString::fromUtf8("tcpRes0"));
        tcpRes0->setGeometry(QRect(23, 130, 16, 17));
        tcpRes1 = new QCheckBox(tcpTab);
        tcpRes1->setObjectName(QString::fromUtf8("tcpRes1"));
        tcpRes1->setGeometry(QRect(43, 130, 16, 17));
        tcpRes2 = new QCheckBox(tcpTab);
        tcpRes2->setObjectName(QString::fromUtf8("tcpRes2"));
        tcpRes2->setGeometry(QRect(63, 130, 16, 17));
        label_27 = new QLabel(tcpTab);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(40, 110, 21, 16));
        tcpSyn = new QCheckBox(tcpTab);
        tcpSyn->setObjectName(QString::fromUtf8("tcpSyn"));
        tcpSyn->setGeometry(QRect(320, 130, 16, 17));
        tcpRst = new QCheckBox(tcpTab);
        tcpRst->setObjectName(QString::fromUtf8("tcpRst"));
        tcpRst->setGeometry(QRect(292, 130, 16, 17));
        tcpAck = new QCheckBox(tcpTab);
        tcpAck->setObjectName(QString::fromUtf8("tcpAck"));
        tcpAck->setGeometry(QRect(233, 130, 16, 17));
        tcpNs = new QCheckBox(tcpTab);
        tcpNs->setObjectName(QString::fromUtf8("tcpNs"));
        tcpNs->setGeometry(QRect(90, 130, 16, 17));
        tcpEce = new QCheckBox(tcpTab);
        tcpEce->setObjectName(QString::fromUtf8("tcpEce"));
        tcpEce->setGeometry(QRect(154, 130, 16, 17));
        tcpUrg = new QCheckBox(tcpTab);
        tcpUrg->setObjectName(QString::fromUtf8("tcpUrg"));
        tcpUrg->setGeometry(QRect(203, 130, 16, 17));
        tcpFin = new QCheckBox(tcpTab);
        tcpFin->setObjectName(QString::fromUtf8("tcpFin"));
        tcpFin->setGeometry(QRect(350, 130, 16, 17));
        tcpPsh = new QCheckBox(tcpTab);
        tcpPsh->setObjectName(QString::fromUtf8("tcpPsh"));
        tcpPsh->setGeometry(QRect(262, 130, 16, 17));
        tcpCwr = new QCheckBox(tcpTab);
        tcpCwr->setObjectName(QString::fromUtf8("tcpCwr"));
        tcpCwr->setGeometry(QRect(121, 130, 16, 17));
        label_28 = new QLabel(tcpTab);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(90, 110, 16, 16));
        label_29 = new QLabel(tcpTab);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(116, 110, 31, 16));
        label_30 = new QLabel(tcpTab);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(151, 110, 21, 16));
        label_31 = new QLabel(tcpTab);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(200, 110, 21, 16));
        label_32 = new QLabel(tcpTab);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(230, 110, 21, 16));
        label_33 = new QLabel(tcpTab);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(260, 110, 21, 16));
        label_34 = new QLabel(tcpTab);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(290, 110, 21, 16));
        label_35 = new QLabel(tcpTab);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(348, 110, 21, 16));
        label_36 = new QLabel(tcpTab);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(318, 110, 21, 16));
        tcpWs = new QLineEdit(tcpTab);
        tcpWs->setObjectName(QString::fromUtf8("tcpWs"));
        tcpWs->setGeometry(QRect(10, 180, 113, 20));
        tcpChecksum = new QLineEdit(tcpTab);
        tcpChecksum->setObjectName(QString::fromUtf8("tcpChecksum"));
        tcpChecksum->setGeometry(QRect(132, 180, 121, 20));
        tcpUrgPointer = new QLineEdit(tcpTab);
        tcpUrgPointer->setObjectName(QString::fromUtf8("tcpUrgPointer"));
        tcpUrgPointer->setGeometry(QRect(260, 180, 113, 20));
        label_37 = new QLabel(tcpTab);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(20, 160, 71, 16));
        label_38 = new QLabel(tcpTab);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(150, 160, 51, 16));
        label_39 = new QLabel(tcpTab);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(270, 160, 71, 16));
        transportTabs->addTab(tcpTab, QString());
        icmpTab = new QWidget();
        icmpTab->setObjectName(QString::fromUtf8("icmpTab"));
        icmpType = new QLineEdit(icmpTab);
        icmpType->setObjectName(QString::fromUtf8("icmpType"));
        icmpType->setGeometry(QRect(10, 30, 113, 20));
        icmpCode = new QLineEdit(icmpTab);
        icmpCode->setObjectName(QString::fromUtf8("icmpCode"));
        icmpCode->setGeometry(QRect(130, 30, 113, 20));
        icmpChecksum = new QLineEdit(icmpTab);
        icmpChecksum->setObjectName(QString::fromUtf8("icmpChecksum"));
        icmpChecksum->setGeometry(QRect(250, 30, 121, 20));
        label_40 = new QLabel(icmpTab);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(20, 10, 31, 16));
        label_41 = new QLabel(icmpTab);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(140, 10, 31, 16));
        label_42 = new QLabel(icmpTab);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(260, 10, 61, 16));
        icmpId = new QLineEdit(icmpTab);
        icmpId->setObjectName(QString::fromUtf8("icmpId"));
        icmpId->setGeometry(QRect(10, 80, 113, 20));
        icmpSeq = new QLineEdit(icmpTab);
        icmpSeq->setObjectName(QString::fromUtf8("icmpSeq"));
        icmpSeq->setGeometry(QRect(130, 80, 113, 20));
        icmpData = new QLineEdit(icmpTab);
        icmpData->setObjectName(QString::fromUtf8("icmpData"));
        icmpData->setGeometry(QRect(10, 130, 361, 20));
        label_43 = new QLabel(icmpTab);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(20, 60, 51, 16));
        label_44 = new QLabel(icmpTab);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(140, 60, 101, 16));
        label_45 = new QLabel(icmpTab);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(20, 110, 46, 13));
        transportTabs->addTab(icmpTab, QString());
        ethTabs = new QTabWidget(centralWidget);
        ethTabs->setObjectName(QString::fromUtf8("ethTabs"));
        ethTabs->setGeometry(QRect(10, 40, 391, 91));
        ethTab = new QWidget();
        ethTab->setObjectName(QString::fromUtf8("ethTab"));
        ethSrc = new QLineEdit(ethTab);
        ethSrc->setObjectName(QString::fromUtf8("ethSrc"));
        ethSrc->setGeometry(QRect(10, 30, 131, 20));
        ethDst = new QLineEdit(ethTab);
        ethDst->setObjectName(QString::fromUtf8("ethDst"));
        ethDst->setGeometry(QRect(150, 30, 131, 20));
        ethType = new QLineEdit(ethTab);
        ethType->setObjectName(QString::fromUtf8("ethType"));
        ethType->setGeometry(QRect(292, 30, 81, 20));
        label = new QLabel(ethTab);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 10, 46, 13));
        label_2 = new QLabel(ethTab);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(160, 10, 71, 16));
        label_3 = new QLabel(ethTab);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(300, 10, 46, 13));
        ethTabs->addTab(ethTab, QString());
        etcTabs = new QTabWidget(centralWidget);
        etcTabs->setObjectName(QString::fromUtf8("etcTabs"));
        etcTabs->setGeometry(QRect(410, 10, 391, 121));
        deviceDescriptionTab = new QWidget();
        deviceDescriptionTab->setObjectName(QString::fromUtf8("deviceDescriptionTab"));
        deviceDescription = new QTextBrowser(deviceDescriptionTab);
        deviceDescription->setObjectName(QString::fromUtf8("deviceDescription"));
        deviceDescription->setGeometry(QRect(-1, -1, 387, 101));
        etcTabs->addTab(deviceDescriptionTab, QString());
        savedPacketsTab = new QWidget();
        savedPacketsTab->setObjectName(QString::fromUtf8("savedPacketsTab"));
        selectPacketBtn = new QPushButton(savedPacketsTab);
        selectPacketBtn->setObjectName(QString::fromUtf8("selectPacketBtn"));
        selectPacketBtn->setGeometry(QRect(2, 44, 72, 23));
        loadPacketFileBtn = new QPushButton(savedPacketsTab);
        loadPacketFileBtn->setObjectName(QString::fromUtf8("loadPacketFileBtn"));
        loadPacketFileBtn->setGeometry(QRect(2, 2, 72, 23));
        packetsView = new QTreeView(savedPacketsTab);
        packetsView->setObjectName(QString::fromUtf8("packetsView"));
        packetsView->setGeometry(QRect(78, -1, 308, 97));
        packetsView->setAutoFillBackground(true);
        packetsView->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        packetsView->setHeaderHidden(true);
        packetsView->header()->setCascadingSectionResizes(true);
        packetsView->header()->setStretchLastSection(false);
        savePacketBtn = new QPushButton(savedPacketsTab);
        savePacketBtn->setObjectName(QString::fromUtf8("savePacketBtn"));
        savePacketBtn->setGeometry(QRect(2, 69, 72, 23));
        sendAll = new QCheckBox(savedPacketsTab);
        sendAll->setObjectName(QString::fromUtf8("sendAll"));
        sendAll->setGeometry(QRect(5, 25, 70, 17));
        etcTabs->addTab(savedPacketsTab, QString());
        stopBtn = new QPushButton(centralWidget);
        stopBtn->setObjectName(QString::fromUtf8("stopBtn"));
        stopBtn->setGeometry(QRect(100, 380, 75, 23));
        MainWindowClass->setCentralWidget(centralWidget);
        QWidget::setTabOrder(deviceBox, sendBtn);
        QWidget::setTabOrder(sendBtn, ipTabs);
        QWidget::setTabOrder(ipTabs, ip4ver);
        QWidget::setTabOrder(ip4ver, ip4ihl);
        QWidget::setTabOrder(ip4ihl, ip4tos);
        QWidget::setTabOrder(ip4tos, ip4len);
        QWidget::setTabOrder(ip4len, ip4id);
        QWidget::setTabOrder(ip4id, ip4offset);
        QWidget::setTabOrder(ip4offset, ip4proto);
        QWidget::setTabOrder(ip4proto, ip4checksum);
        QWidget::setTabOrder(ip4checksum, ip4res);
        QWidget::setTabOrder(ip4res, ip4df);
        QWidget::setTabOrder(ip4df, ip4mf);
        QWidget::setTabOrder(ip4mf, ip4ttl);
        QWidget::setTabOrder(ip4ttl, ip4src);
        QWidget::setTabOrder(ip4src, ip4dest);
        QWidget::setTabOrder(ip4dest, transportTabs);
        QWidget::setTabOrder(transportTabs, udpSrc);
        QWidget::setTabOrder(udpSrc, udpDst);
        QWidget::setTabOrder(udpDst, udpLen);
        QWidget::setTabOrder(udpLen, udpChecksum);
        QWidget::setTabOrder(udpChecksum, tcpSrc);
        QWidget::setTabOrder(tcpSrc, tcpDst);
        QWidget::setTabOrder(tcpDst, tcpSeqNum);
        QWidget::setTabOrder(tcpSeqNum, tcpAckNum);
        QWidget::setTabOrder(tcpAckNum, tcpOffset);
        QWidget::setTabOrder(tcpOffset, icmpType);
        QWidget::setTabOrder(icmpType, tcpRes0);
        QWidget::setTabOrder(tcpRes0, tcpRes1);
        QWidget::setTabOrder(tcpRes1, tcpRes2);
        QWidget::setTabOrder(tcpRes2, tcpNs);
        QWidget::setTabOrder(tcpNs, tcpCwr);
        QWidget::setTabOrder(tcpCwr, tcpEce);
        QWidget::setTabOrder(tcpEce, tcpUrg);
        QWidget::setTabOrder(tcpUrg, tcpAck);
        QWidget::setTabOrder(tcpAck, tcpPsh);
        QWidget::setTabOrder(tcpPsh, tcpRst);
        QWidget::setTabOrder(tcpRst, tcpSyn);
        QWidget::setTabOrder(tcpSyn, tcpFin);
        QWidget::setTabOrder(tcpFin, tcpWs);
        QWidget::setTabOrder(tcpWs, tcpChecksum);
        QWidget::setTabOrder(tcpChecksum, tcpUrgPointer);
        QWidget::setTabOrder(tcpUrgPointer, icmpCode);
        QWidget::setTabOrder(icmpCode, icmpChecksum);
        QWidget::setTabOrder(icmpChecksum, icmpId);
        QWidget::setTabOrder(icmpId, icmpSeq);
        QWidget::setTabOrder(icmpSeq, icmpData);
        QWidget::setTabOrder(icmpData, ethTabs);
        QWidget::setTabOrder(ethTabs, ethSrc);
        QWidget::setTabOrder(ethSrc, ethDst);
        QWidget::setTabOrder(ethDst, ethType);
        QWidget::setTabOrder(ethType, etcTabs);
        QWidget::setTabOrder(etcTabs, deviceDescription);
        QWidget::setTabOrder(deviceDescription, selectPacketBtn);
        QWidget::setTabOrder(selectPacketBtn, loadPacketFileBtn);
        QWidget::setTabOrder(loadPacketFileBtn, packetsView);
        QWidget::setTabOrder(packetsView, savePacketBtn);
        QWidget::setTabOrder(savePacketBtn, sendAll);
        QWidget::setTabOrder(sendAll, stopBtn);

        retranslateUi(MainWindowClass);

        ipTabs->setCurrentIndex(0);
        transportTabs->setCurrentIndex(1);
        ethTabs->setCurrentIndex(0);
        etcTabs->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindowClass);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindowClass)
    {
        MainWindowClass->setWindowTitle(QApplication::translate("MainWindowClass", "PacketGenerator", 0, QApplication::UnicodeUTF8));
        sendBtn->setText(QApplication::translate("MainWindowClass", "Send", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("MainWindowClass", "Version", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MainWindowClass", "IHL", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindowClass", "ToS", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindowClass", "Packet Length", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("MainWindowClass", "Identifier", 0, QApplication::UnicodeUTF8));
        ip4res->setText(QString());
        ip4df->setText(QString());
        label_9->setText(QApplication::translate("MainWindowClass", "Res.", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("MainWindowClass", "DF", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("MainWindowClass", "MF", 0, QApplication::UnicodeUTF8));
        ip4mf->setText(QString());
        label_12->setText(QApplication::translate("MainWindowClass", "Fragment Offset", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MainWindowClass", "TTL", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("MainWindowClass", "Protocol", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("MainWindowClass", "Checksum", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("MainWindowClass", "Source", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("MainWindowClass", "Destination", 0, QApplication::UnicodeUTF8));
        ipTabs->setTabText(ipTabs->indexOf(ip4Tab), QApplication::translate("MainWindowClass", "IPv4", 0, QApplication::UnicodeUTF8));
        ipTabs->setTabText(ipTabs->indexOf(ip6Tab), QApplication::translate("MainWindowClass", "IPv6", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("MainWindowClass", "Source port", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("MainWindowClass", "Destination port", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("MainWindowClass", "Datagram Legnth", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("MainWindowClass", "Checksum", 0, QApplication::UnicodeUTF8));
        transportTabs->setTabText(transportTabs->indexOf(udpTab), QApplication::translate("MainWindowClass", "UDP", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("MainWindowClass", "Source port", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("MainWindowClass", "Destination port", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("MainWindowClass", "Sequence number", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("MainWindowClass", "Acknowledgment number", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("MainWindowClass", "Offset", 0, QApplication::UnicodeUTF8));
        tcpRes0->setText(QString());
        tcpRes1->setText(QString());
        tcpRes2->setText(QString());
        label_27->setText(QApplication::translate("MainWindowClass", "Res.", 0, QApplication::UnicodeUTF8));
        tcpSyn->setText(QString());
        tcpRst->setText(QString());
        tcpAck->setText(QString());
        tcpNs->setText(QString());
        tcpEce->setText(QString());
        tcpUrg->setText(QString());
        tcpFin->setText(QString());
        tcpPsh->setText(QString());
        tcpCwr->setText(QString());
        label_28->setText(QApplication::translate("MainWindowClass", "NS", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("MainWindowClass", "CWR", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("MainWindowClass", "ECE", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("MainWindowClass", "URG", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("MainWindowClass", "ACK", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("MainWindowClass", "PSH", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("MainWindowClass", "RST", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("MainWindowClass", "FIN", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("MainWindowClass", "SYN", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("MainWindowClass", "Window size", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("MainWindowClass", "Checksum", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("MainWindowClass", "Urgent pointer", 0, QApplication::UnicodeUTF8));
        transportTabs->setTabText(transportTabs->indexOf(tcpTab), QApplication::translate("MainWindowClass", "TCP", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("MainWindowClass", "Type", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("MainWindowClass", "Code", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("MainWindowClass", "Checksum", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("MainWindowClass", "Identifier", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("MainWindowClass", "Sequence number", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("MainWindowClass", "Data", 0, QApplication::UnicodeUTF8));
        transportTabs->setTabText(transportTabs->indexOf(icmpTab), QApplication::translate("MainWindowClass", "ICMP", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindowClass", "Source", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindowClass", "Destination", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindowClass", "Type", 0, QApplication::UnicodeUTF8));
        ethTabs->setTabText(ethTabs->indexOf(ethTab), QApplication::translate("MainWindowClass", "Ethernet", 0, QApplication::UnicodeUTF8));
        etcTabs->setTabText(etcTabs->indexOf(deviceDescriptionTab), QApplication::translate("MainWindowClass", "Device Description", 0, QApplication::UnicodeUTF8));
        selectPacketBtn->setText(QApplication::translate("MainWindowClass", "Select packet", 0, QApplication::UnicodeUTF8));
        loadPacketFileBtn->setText(QApplication::translate("MainWindowClass", "Load file", 0, QApplication::UnicodeUTF8));
        savePacketBtn->setText(QApplication::translate("MainWindowClass", "Save packet", 0, QApplication::UnicodeUTF8));
        sendAll->setText(QApplication::translate("MainWindowClass", "Send all", 0, QApplication::UnicodeUTF8));
        etcTabs->setTabText(etcTabs->indexOf(savedPacketsTab), QApplication::translate("MainWindowClass", "Saved Packets", 0, QApplication::UnicodeUTF8));
        stopBtn->setText(QApplication::translate("MainWindowClass", "Stop", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindowClass: public Ui_MainWindowClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
